# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee154c016635df38332dfe97a1f1e98353cfd55506dea487224d148eaaab775b7346a283d3c3c1b8a59f8f31be0860fc5566f449d4362db27c0e44b81e5821dc

test:
  secret_key_base: 66bdbaa46e23bab0240a4538065bd28bb9be4d8f9250f6dc0f41f6a2e60101fa8d265bd755c16071b15e4513c7cc0b320112af15b1ceb80a9d3971374edc4860

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
